CLASS zbp_bookingsupplement_u DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF zi_travel_u .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zbp_bookingsupplement_u IMPLEMENTATION.
ENDCLASS.
